<?php

//создаем фасад который возвращает ячейку в контейнере

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class MyFacade extends Facade {

  protected static function getFacadeAccessor() {

    //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub

    //вернем название ячейки 'cellname', в которую привязан объект к контейнеру
    return 'cellname';
  }

}

